name: Post coverage comment

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  test:
    name: Display coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: tests.yml
          workflow_conclusion: success
          name: coverage
          if_no_artifact_found: warn

      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          VERBOSE: true
          COMMENT_TEMPLATE: 'Coverage info:<br> {% for file_coverage in coverage.files.values() %} {% if not file_coverage.path.startswith("tests") %} {{ file_coverage.path }}: {{ ((file_coverage.info.percent_covered * 100)|int) }}%<br> {% endif %} {% endfor %}{{ marker }}'